<a href="https://colab.research.google.com/github/vishnu-777/python-datascience/blob/main/matirx_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.arange(start=6,stop=15).reshape(3,3)
print(b)
sum=(np.add(a,b))
print("sum is ",sum)
print("multiplcation is",np.multiply(a,b))
print("division is",np.divide(a,b))
print("subtraction is",np.subtract(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
sum is  [[ 7  9 11]
 [13 15 17]
 [19 21 23]]
multiplcation is [[  6  14  24]
 [ 36  50  66]
 [ 84 104 126]]
division is [[0.16666667 0.28571429 0.375     ]
 [0.44444444 0.5        0.54545455]
 [0.58333333 0.61538462 0.64285714]]
subtraction is [[-5 -5 -5]
 [-5 -5 -5]
 [-5 -5 -5]]
