<a href="https://colab.research.google.com/github/vishnu-777/python-datascience/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
arr=np.array([1,2,3,'a'])
print(arr)
print(type(arr))

arr2=np.linspace(start=1,stop=6,num=15,endpoint=True,retstep=False)
print(arr2)
print(type(arr2))
print(np.shape(arr2))
print(np.shape(arr))

arr3=np.arange(start=1,stop=11,step=3)
print(arr3)

arr4=np.ones((2,2))
print(arr4)

arr5=np.zeros((3,2))
print("\n",arr5)

arr6=np.random.rand(1,2)
print(arr6)

arr7=np.logspace(start=1,stop=10,num=5,base=10)
print(arr7)

['1' '2' '3' 'a']
<class 'numpy.ndarray'>
[1.         1.35714286 1.71428571 2.07142857 2.42857143 2.78571429
 3.14285714 3.5        3.85714286 4.21428571 4.57142857 4.92857143
 5.28571429 5.64285714 6.        ]
<class 'numpy.ndarray'>
(15,)
(4,)
[ 1  4  7 10]
[[1. 1.]
 [1. 1.]]

 [[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.41087577 0.71635224]]
[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]
